= Entwicklerdokumentation

== Einführung und Ziele
* Aufgabenstellung
* Qualitätsziele

== Randbedingungen
* Hardware-Vorgaben
* Software-Vorgaben
* Vorgaben zum Betrieb des Software

== Kontextabgrenzung
* Externe Schnittstellen

== Lösungsstrategie
Kurzer Überblick über Ihre grundlegenden Entscheidungen und Lösungsansätze, die jeder, der mit der Architektur zu tun hat, verstanden haben sollte.

* Nutzung von Controllern, um Personen zu beschreiben
** Im AKD haben wir noch für jede Mitarbeitergruppe eine eigene Klasse mit Methoden erstellt.
** In Spring haben wir uns aber dafür entschieden, jeder Gruppe einen eigenen URL Namespace zu geben (z.B. /admin), auf den nur Personen mit dieser Rolle zugreifen können
** Personenmethoden im AKD wurden nun zu RequestMappings.
*** So ist aus der Boss.addEvents() Methode ein RequestMapping auf /admin/events/add geworden.

* Keine Nutzung der Visitor-Rolle
** Im AKD haben wir noch eine Visitor-Rolle gespeichert.
** Diese haben wir aber im Programm gesprichten, da die Visitor-Rolle mit einem nicht angemeldeten Nutzer gleichzusetzen ist.

* Gruppierung der Requests nach Aufgaben, nicht nach Personen
** Zuerst wollten wir jeweils einen AdminController, CookController,..., anlegen.
** Diese Idee haben wir aber verworfen, da wir es später übersichtlicher fanden, die Controller nach den Aufgaben zu sortieren. So sieht man nun z.B. im EventController sofort, wer welche Rechte im Bezug auf die Events hat, ohne sich durch alle PersonenController suchen zu müssen. 
** Damit einhergehend ist auch die nächste Entscheidung gefallen

* Keine Nutzung von @Preauthorize
** Diese haben zuerst genutzt, um jeder Person ihren PersonenController zuzuweisen
** Mit der Erstellung von Namespaces (z.B. /admin) in der Application Klasse haben wir allerdings einen gleichwertigen Weg gefunden, der uns Aufgaben Controller schreiben lässt.

* Verwenden eigener `Bill` Klasse, statt `Bill extends Salespoint.Order` oder `Order order` als Attribut von `Bill`
** Obwohl die Klasse `Order` alle Funktionalitäten enthält, die man für eine Rechnung braucht, gab es einige Umsetzungsschwierigkeiten:
*** Das erweitern der Klasse `Order` ist nicht möglich, da der *default constructor* private und somit in der Kindklasse nicht erreichbar ist. Dies führt wiederrum zu einer Exception von Spring `No default constructor found; nested exception is java.lang.NoSuchMethodException`
*** Durch das Erstellen einer `Bill` Klasse mit einem Attribut `Order order` stellten sich einige Umwege beim Suchen der Aktiven und Archivierten Rechnungen ein. Desweiteren gab es einen Konflikt mit dem Schlagwort *Order* (=sortieren) und dem Suchen nach dem Attribut `Order order` in SQL.
** Statt den obigen Designs haben wir uns deshalb zu einer unabhängigen Rechnungsklasse `Bill` entschieden, welche ein `Set<BillItem> items` enthält und diese wiederrum eine `@OneToOne` Verbindung zu Produkten die auf der aktuellen Tageskarte stehen. Somit ist auch sichergestellt, dass ausschließlich Produkte der Tageskarte verkauft werden.

* Verwenden von Java-seitiger DB-Suche, statt effizienterer Implementierung in dem Repository von `Expense`
** Unsere Klasse `Expense` steht für Ausgaben und erweitert die Klasse `Salespoint.AccountancyEntry`. Da das Repository  `AccountancyEntryRepository` allerdings package-private ist, lässt sich dieses nicht erweitern und dort dementsprechend keine weiteren Suchfunktionen eintragen.
** `ExpenseRepository extends Accountancy` kommt ebenfalls nicht in Frage, da `Salespoint.Accountancy` selbst kein Repository ist und unseres dann nichtmehr als Bean erkannt werden würde.
** Ein vollständig eigenes Repository `ExpenseRepository extends SalespointRepository` ist nicht sinnvoll, da dann jegliche Funktionalitäten von Accountancy verloren gehen würden, wie etwa `package-private setDate()`, welches für unsere Verwaltung notwendig ist.
** Die Filter für die Ausgaben lassen sich nun in dem Template beliebig setzen und werden dann im Controller angewendet, um das gewünschte Ergebnis zu liefern.

* Benenne Table in Desk um
** Da wir große Schwierigkeiten bekommen haben, die Tables von WineTavern, HTML und MySQL auseinander zu halten, haben wir uns beschlossen, die WineTavern Tables in Desks umzubennenen.

* Benenne Person in Employee um
** Zuerst sollten alle externen und internen Personen ein Person-Objekt bekommen. Dieses ist allerdings fest mit einem UserAccount verbunden. Da sich externe (Künstler) allerdings nicht in das System einloggen müssen, haben wir die externen Personen zu "External" gemacht, während Interne nun "Employee" sind. 

* Ziehe Integration- und Unittests auseinander
** Als erstes wollten wir alle Tests, die zu einer Klasse gehören, in eine Klasse packen. Da so aber die Unittests sehr lange zum ausführen brauchten (Da im Hintergrund alles Nötige für die Integrationtests auch geladen wurde), haben wir uns entscheiden, diese in unterschiedliche Klassen zu stecken.

* Nutze Mockito um Objekte zu mocken
** Am Anfang haben wir in einem Unittest auch alle nötigen Hilfsobjekte erzeugt. Da so aber bei Fehlern in der Hilfsklasse auch Fehler in der anderen Klasse entstanden, haben wir uns entscheiden, Mocks zu nutzen. Dadurch sind die Unittests einer Klasse unabhängig von den Fehlern anderer Klassen.

== Bausteinsicht
* Package-Diagramme

== Entwurfsentscheidungen
* Architektur
* Verwendete Muster
* Persistenz
* Benutzeroberfläche

[appendix]
== Glossar
